Monitoring 2 (HW23)
LexRich/microservices pull request #5
Opened 2018-01-18 19:17 UTC by LexRich

Настройка дашбордов графаны и алерты

2018-01-19 13:57 UTC, chromko requested changes
Поправить несколько замечаний, написанных ниже.

2018-01-19 13:57 UTC, chromko commented on prometheus/alert.rules
> +﻿# Alert for any instance that is unreachable for >5 minutes.
Правила в старом формате впринципе можно убирать

2018-01-19 13:57 UTC, chromko commented on docker-compose.yml
> +    image: ${USER_NAME}/alertmanager
Сейчас есть неоднозначность с названиями переменных USERNAME и USER_NAME. Нужно прийти к чему-то одному

2018-01-23 07:57 UTC, LexRich commented on prometheus/alert.rules
> +﻿# Alert for any instance that is unreachable for >5 minutes.
В старом формате матерился на вторую строку сразу

2018-01-23 08:03 UTC, LexRich commented
Внесены изменения

2018-02-16 10:18 UTC, merged